In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Fill in the path to your data here...
year = 2015

file1 = f"RetroSheet/gl{year}.txt"
df = pd.read_csv(file1, header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160
0,20150405,0,Sun,SLN,NL,1,CHN,NL,1,3,0,54,N,NaN,NaN,NaN,CHI11,35055.0,184,110010000,000000000,36,10,3,0,0,3,0,0,0,4,1,11,4,1,0,0,10,4,0,0,0,0,27,8,0,1,0,0,32,5,3,0,0,0,0,0,0,2,0,12,1,0,0,0,7,6,3,3,0,0,27,8,2,0,0,0,wintm901,Mike Winters,wegnm901,Mark Wegner,fostm901,Marty Foster,muchm901,Mike Muchlinski,NaN,(none),NaN,(none),mathm001,Mike Matheny,maddj801,Joe Maddon,waina001,Adam Wainwright,lestj001,Jon Lester,roset001,Trevor Rosenthal,hollm001,Matt Holliday,waina001,Adam Wainwright,lestj001,Jon Lester,carpm002,Matt Carpenter,5,heywj001,Jason Heyward,9,hollm001,Matt Holliday,7,peraj001,Jhonny Peralta,6,adamm002,Matt Adams,3,moliy001,Yadier Molina,2,wongk001,Kolten Wong,4,jay-j001,Jon Jay,8,waina001,Adam Wainwright,1,fowld001,Dexter Fowler,8,solej001,Jorge Soler,9,rizza001,Anthony Rizzo,3,casts001,Starlin Castro,6,coghc001,Chris Coghlan,7,olt-m001,Mike Olt,5,rossd001,David Ross,2,lestj001,Jon Lester,1,lastt001,Tommy La Stella,4,NaN,Y
1,20150406,0,Mon,MIN,AL,1,DET,AL,1,0,4,51,D,NaN,NaN,NaN,DET05,45030.0,150,000000000,03000100x,31,5,0,0,0,0,0,0,0,0,0,6,0,0,1,0,4,2,4,4,0,0,24,6,0,0,2,0,31,10,1,1,2,4,0,1,0,2,0,6,3,0,2,0,6,2,0,0,0,0,27,9,0,0,1,0,westj901,Joe West,danlk901,Kerwin Danley,barkl901,Lance Barksdale,reybd901,D.J. Reyburn,NaN,(none),NaN,(none),molip001,Paul Molitor,ausmb001,Brad Ausmus,pricd001,David Price,hughp001,Phil Hughes,nathj001,Joe Nathan,martj006,J.D. Martinez,hughp001,Phil Hughes,pricd001,David Price,santd001,Danny Santana,6,dozib001,Brian Dozier,4,mauej001,Joe Mauer,3,huntt001,Torii Hunter,9,vargk001,Kennys Vargas,10,plout001,Trevor Plouffe,5,arcio001,Oswaldo Arcia,7,suzuk001,Kurt Suzuki,2,schaj002,Jordan Schafer,8,davir003,Rajai Davis,8,kinsi001,Ian Kinsler,4,cabrm001,Miguel Cabrera,3,martv001,Victor Martinez,10,martj006,J.D. Martinez,9,cespy001,Yoenis Cespedes,7,castn001,Nick Castellanos,5,avila001,Alex Avila,2,iglej001,Jose Iglesias,6,NaN,Y
2,20150406,0,Mon,CLE,AL,1,HOU,AL,1,0,2,51,N,NaN,NaN,NaN,HOU03,43753.0,150,000000000,00000101x,29,3,0,0,0,0,0,0,0,3,0,7,0,0,1,0,5,2,2,2,0,0,24,10,0,0,0,0,25,3,0,0,0,2,0,1,0,2,0,7,1,0,0,0,2,3,0,0,0,0,27,13,0,0,1,0,barrt901,Ted Barrett,herna901,Angel Hernandez,barrs901,Scott Barry,conrc901,Chris Conroy,NaN,(none),NaN,(none),frant001,Terry Francona,hinca001,A.J. Hinch,keucd001,Dallas Keuchel,klubc001,Corey Kluber,gregl001,Luke Gregerson,sprig001,George Springer,klubc001,Corey Kluber,keucd001,Dallas Keuchel,bourm001,Michael Bourn,8,kipnj001,Jason Kipnis,4,branm003,Michael Brantley,7,santc002,Carlos Santana,3,gomey001,Yan Gomes,2,mossb001,Brandon Moss,9,rabur001,Ryan Raburn,10,chisl001,Lonnie Chisenhall,5,ramij003,Jose Ramirez,6,altuj001,Jose Altuve,4,sprig001,George Springer,9,valbl001,Luis Valbuena,5,gatte001,Evan Gattis,10,cartc002,Chris Carter,3,castj006,Jason Castro,2,lowrj001,Jed Lowrie,6,rasmc001,Colby Rasmus,7,marij002,Jake Marisnick,8,NaN,Y
3,20150406,0,Mon,CHA,AL,1,KCA,AL,1,1,10,51,D,NaN,NaN,NaN,KAN06,40085.0,170,000000100,01201051x,28,5,1,0,1,1,0,0,1,2,0,3,0,0,3,0,3,3,10,10,1,0,24,7,0,0,2,0,34,13,3,0,2,9,1,0,2,5,1,3,2,0,1,0,8,4,1,1,0,0,27,16,0,0,3,0,laynj901,Jerry Layne,wendh902,Hunter Wendelstedt,davib902,Bob Davidson,rackd901,David Rackley,NaN,(none),NaN,(none),ventr001,Robin Ventura,yoste001,Ned Yost,venty001,Yordano Ventura,samaj001,Jeff Samardzija,NaN,(none),peres002,Salvador Perez,samaj001,Jeff Samardzija,venty001,Yordano Ventura,eatoa002,Adam Eaton,8,cabrm002,Melky Cabrera,7,abrej003,Jose Abreu,3,laroa001,Adam LaRoche,10,garca003,Avisail Garcia,9,ramia003,Alexei Ramirez,6,gillc001,Conor Gillaspie,5,flowt001,Tyler Flowers,2,johnm006,Micah Johnson,4,escoa003,Alcides Escobar,6,mousm001,Mike Moustakas,5,cainl001,Lorenzo Cain,8,hosme001,Eric Hosmer,3,morak001,Kendrys Morales,10,gorda001,Alex Gordon,7,riosa002,Alex Rios,9,peres002,Salvador Perez,2,infao001,Omar Infante,4,NaN,Y
4,20150406,0,Mon,TOR,AL,1,NYA,AL,1,6,1,54,D,NaN,NaN,NaN,NYC21,48469.0,179,005000100,000001000,33,6,0,0,2,5,1,0,0,5,0,12,2,0,0,0,6,3,1,1,0,0,27,4,0,0,0,0,29,3,0,0,1,1,0,0,1,3,0,5,0,1,0,0,5,6,5,5,0,0,27,6,1,0,0,0,culbf901,Fieldin Culbreth,reynj901,Jim Reynolds,mealj901,Jerry Meals,schrp901,Paul Schrieber,NaN,(none),NaN,(none),gibbj001,John Gibbons,giraj001,Joe Girardi,hutcd001,Drew Hutchison,tanam001,Masahiro Tanaka,NaN,(none),NaN,(none),hutcd001,Drew Hutchison,tanam001,Masahiro Tanaka,reyej001,Jose Reyes,6,martr004,Russell Martin,2,bautj002,Jose Bautista,9,encae001,Edwin Encarnacion,3,donaj001,Josh Donaldson,5,navad001,Dioner Navarro,10,pompd001,Dalton Pompey,8,pillk001,Kevin Pillar,7,travd001,Devon Travis,4,ellsj001,Jacoby Ellsbury,8,gardb001,Brett Gardner,7,beltc001,Carlos Beltran,9,teixm001,Mark Teixeira,3,mccab002,Brian McCann,2,headc001,Chase Headley,5,rodra001,Alex Rodriguez,10,drews001,Stephen Drew,4,gregd001,Didi Gregorius,6,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2424,20151004,0,Sun,CHN,NL,162,MIL,NL,162,3,1,54,D,NaN,NaN,NaN,MIL06,32959.0,164,300000000,001000000,32,7,0,0,0,2,0,0,1,4,0,9,2,1,2,0,7,4,1,1,0,0,27,12,0,0,1,0,28,3,2,0,0,1,1,0,0,2,0,6,1,0,1,0,3,4,3,3,1,0,27,8,0,0,3,0,herna901,Angel Hernandez,conrc901,Chris Conroy,barrt901,Ted Barrett,hamaa901,Adam Hamari,NaN,(none),NaN,(none),maddj801,Joe Maddon,counc001,Craig Counsell,hared001,Dan Haren,lopej004,Jorge Lopez,woodt004,Travis Wood,rizza001,Anthony Rizzo,hared001,Dan Haren,lopej004,Jorge Lopez,jacka001,Austin Jackson,8,coghc001,Chris Coghlan,9,bryak001,Kris Bryant,5,rizza001,Anthony Rizzo,3,casts001,Starlin Castro,4,denoc001,Chris Denorfia,7,montm001,Miguel Montero,2,russa002,Addison Russell,6,hared001,Dan Haren,1,genns001,Scooter Gennett,4,petes002,Shane Peterson,9,linda001,Adam Lind,3,davik003,Khris Davis,7,santd002,Domingo Santana,8,pereh001,Hernan Perez,5,seguj002,Jean Segura,6,maldm001,Martin Maldonado,2,lopej004,Jorge Lopez,1,NaN,Y
2425,20151004,0,Sun,WAS,NL,162,NYN,NL,162,0,1,51,D,NaN,NaN,NaN,NYC20,41631.0,154,000000000,00000001x,29,2,1,0,0,0,0,0,0,2,0,14,1,0,0,0,4,3,1,1,0,0,24,10,0,0,2,0,27,5,2,0,1,1,0,0,1,2,0,7,0,0,2,0,5,7,0,0,0,0,27,7,0,0,0,0,wolfj901,Jim Wolf,davig901,Gerry Davis,cuzzp901,Phil Cuzzi,randt901,Tony Randazzo,NaN,(none),NaN,(none),willm003,Matt Williams,collt801,Terry Collins,clipt001,Tyler Clippard,treib001,Blake Treinen,famij001,Jeurys Familia,granc001,Curtis Granderson,roart001,Tanner Roark,degrj001,Jacob deGrom,renda001,Anthony Rendon,5,turnt001,Trea Turner,4,harpb003,Bryce Harper,9,wertj001,Jayson Werth,7,robic001,Clint Robinson,3,desmi001,Ian Desmond,6,taylm002,Michael Taylor,8,sevep001,Pedro Severino,2,roart001,Tanner Roark,1,granc001,Curtis Granderson,9,wrigd002,David Wright,5,murpd006,Daniel Murphy,4,cespy001,Yoenis Cespedes,8,dudal001,Lucas Duda,3,darnt001,Travis d'Arnaud,2,confm001,Michael Conforto,7,tejar001,Ruben Tejada,6,degrj001,Jacob deGrom,1,NaN,Y
2426,20151004,0,Sun,MIA,NL,162,PHI,NL,162,2,7,51,D,NaN,NaN,NaN,PHI13,21734.0,149,101000000,00011041x,35,8,2,0,1,1,0,0,0,1,0,11,0,0,1,0,7,4,7,7,0,0,24,6,0,0,1,0,33,10,5,1,0,7,0,0,0,5,1,3,0,0,1,0,7,4,1,1,0,0,27,11,1,0,1,0,reybd901,D.J. Reyburn,drakr901,Rob Drake,westj901,Joe West,danlk901,Kerwin Danley,NaN,(none),NaN,(none),jennd801,Dan Jennings,mackp101,Pete Mackanin,garcl005,Luis Garcia,riena001,Andre Rienzo,NaN,(none),galvf001,Freddy Galvis,conla001,Adam Conley,buchd001,David Buchanan,gordd002,Dee Gordon,4,yelic001,Christian Yelich,8,ozunm001,Marcell Ozuna,9,bourj002,Justin Bour,3,dietd001,Derek Dietrich,7,mcgec001,Casey McGehee,5,telit001,Tomas Telis,2,rojam002,Miguel Rojas,6,conla001,Adam Conley,1,galvf001,Freddy Galvis,6,altha001,Aaron Altherr,8,franm004,Maikel Franco,5,ruf-d001,Darin Ruf,7,franj004,Jeff Francoeur,9,blana001,Andres Blanco,4,krate001,Erik Kratz,3,ruppc001,Cameron Rupp,2,buchd001,David Buchanan,1,NaN,Y
2427,20151004,0,Sun,CIN,NL,162,PIT,NL,162,0,4,51,D,NaN,NaN,NaN,PIT08,35362.0,183,000000000,10010110x,31,6,0,0,0,0,0,0,0,3,0,10,0,1,0,0,7,5,4,4,0,0,24,9,0,0,0,0,36,13,5,0,1,4,0,0,0,1,0,7,0,1,0,0,9,4,0,0,1,0,27,7,0,0,0,0,welkt901,Tim Welke,ticht901,Todd Tichenor,timmt901,Tim Timmons,everm901,Mike Everitt,NaN,(none),NaN,(none),pricb801,Bryan Price,hurdc001,Clint Hurdle,happj001,J.A. Happ,smitj004,Josh Smith,NaN,(none),walkn001,Neil Walker,smitj004,Josh Smith,happj001,J.A. Happ,bourj001,Jason Bourgeois,8,suare001,Eugenio Suarez,6,vottj001,Joey Votto,3,philb001,Brandon Phillips,4,frazt001,Todd Frazier,5,brucj001,Jay Bruce,9,duvaa001,Adam Duvall,7,penab002,Brayan Pena,2,smitj004,Josh Smith,1,polag001,Gregory Polanco,9,harrj002,Josh Harrison,5,mccua001,Andrew McCutchen,8,walkn001,Neil Walker,4,marts002,Starling Marte,7,alvap001,Pedro Alvarez,3,cervf001,Francisco Cervelli,2,mercj002,Jordy Mercer,6,happj001,J.A. Happ,1,NaN,Y
2428,20151004,0,Sun,COL,NL,162,SFN,NL,162,7,3,54,D,NaN,NaN,NaN,SFO03,41399.0,185,000000007,200001000,37,9,0,1,1,7,0,0,0,2,0,2,1,0,0,0,5,6,3,3,0,0,27,15,0,0,2,0,35,12,1,0,0,3,1,0,0,4,0,3,0,1,2,0,10,11,7,7,0,0,27,5,1,0,0,0,torrc901,Carlos Torres,fleta901,Andy Fletcher,mealj901,Jerry Meals,bakej902,Jordan Baker,NaN,(none),NaN,(none),weisw001,Walt Weiss,bochb002,Bruce Bochy,brotr001,Rex Brothers,kontg001,George Kontos,NaN,(none),mornj001,Justin Morneau,bergc001,Christian Bergman,cainm001,Matt Cain,blacc001,Charlie Blackmon,8,reyej001,Jose Reyes,6,gonzc001,Carlos Gonzalez,9,arenn001,Nolan Arenado,5,dickc002,Corey Dickerson,7,rosaw001,Wilin Rosario,3,descd001,Daniel Descalso,4,garnd001,Dustin Garneau,2,bergc001,Christian Bergman,1,pagaa001,Angel Pagan,8,tomlk001,Kelby Tomlinson,4,duffm002,Matt Duffy,5,poseb001,Buster Posey,3,parkj002,Jarrett Parker,9,willm008,Mac Williamson,7,noonn001,Nick Noonan,6,willj005,Jackson Williams,2,cainm001,Matt Cain,1,NaN,Y

In [4]:
file1 = f"RetroSheet/teams.csv"
df = pd.read_csv(file1, header=None)

In [11]:
teams_col = ["TEAM", "LEAGUE", "CITY", "NICKNAME", "FIRST", "LAST"]

In [12]:
df.columns = teams_col

In [23]:
df.drop(index=df.index[0], axis=0, inplace=True)

In [26]:
df.dtypes

TEAM        object
LEAGUE      object
CITY        object
NICKNAME    object
FIRST       object
LAST        object
dtype: object

In [27]:
df["FIRST"] = df["FIRST"].astype(int)
df["LAST"] = df["LAST"].astype(int)

In [29]:
df.head()

  TEAM LEAGUE             CITY          NICKNAME  FIRST  LAST
1  ACY    ECL    Atlantic City  Bacharach Giants   1916  1929
2  AGS    NaN      Augie Galan         All Stars   1944  1944
3  AKR    NaN            Akron             Grays   1933  1933
4  ALS    NaN  American League         All Stars   1926  1935
5  ALT     UA          Altoona    Mountain Citys   1884  1884

In [35]:
nl = df[df.LEAGUE == "NL"][df.LAST == 2023]
nl

/tmp/ipykernel_24061/145440670.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  nl = df[df.LEAGUE == "NL"][df.LAST == 2023]

    TEAM LEAGUE           CITY      NICKNAME  FIRST  LAST
7    ARI     NL        Arizona  Diamondbacks   1998  2023
19   ATL     NL        Atlanta        Braves   1966  2023
67   CHN     NL        Chicago          Cubs   1876  2023
73   CIN     NL     Cincinnati          Reds   1890  2023
89   COL     NL       Colorado       Rockies   1993  2023
147  LAN     NL    Los Angeles       Dodgers   1958  2023
154  MIA     NL          Miami       Marlins   2012  2023
187  NYN     NL       New York          Mets   1962  2023
198  PHI     NL   Philadelphia      Phillies   1883  2023
203  PIT     NL     Pittsburgh       Pirates   1887  2023
218  SDN     NL      San Diego        Padres   1969  2023
221  SFN     NL  San Francisco        Giants   1958  2023
232  SLN     NL      St. Louis     Cardinals   1892  2023
251  WAS     NL     Washington     Nationals   2005  2023

In [36]:
al = df[df.LEAGUE == "AL"][df.LAST == 2023]
al

/tmp/ipykernel_24061/572214545.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  al = df[df.LEAGUE == "AL"][df.LAST == 2023]

    TEAM LEAGUE         CITY    NICKNAME  FIRST  LAST
6    ANA     AL      Anaheim      Angels   1997  2023
21   BAL     AL    Baltimore     Orioles   1954  2023
37   BOS     AL       Boston     Red Sox   1901  2023
64   CHA     AL      Chicago   White Sox   1901  2023
80   CLE     AL    Cleveland     Indians   1901  2023
106  DET     AL      Detroit      Tigers   1901  2023
138  KCA     AL  Kansas City      Royals   1969  2023
157  MIN     AL    Minnesota       Twins   1961  2023
185  NYA     AL     New York     Yankees   1903  2023
189  OAK     AL      Oakland   Athletics   1968  2023
220  SEA     AL      Seattle    Mariners   1977  2023
240  TBA     AL    Tampa Bay  Devil Rays   1998  2023
241  TEX     AL        Texas     Rangers   1972  2023
246  TOR     AL      Toronto   Blue Jays   1977  2023

In [37]:
len(nl)

14

In [38]:
len(al)

14

In [45]:
file1 = f"RetroSheet/ballparks.csv"
df = pd.read_csv(file1, header=None)
df.shape

(554, 9)

In [46]:
file1 = f"RetroSheet/biofile.csv"
df = pd.read_csv(file1, header=None)
df.shape

/tmp/ipykernel_24061/3584720123.py:2: DtypeWarning: Columns (23,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file1, header=None)

(25757, 33)

In [47]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32
0,PLAYERID,LAST,FIRST,NICKNAME,BIRTHDATE,BIRTH.CITY,BIRTH.STATE,BIRTH.COUNTRY,PLAY.DEBUT,PLAY.LASTGAME,MGR.DEBUT,MGR.LASTGAME,COACH.DEBUT,COACH.LASTGAME,UMP.DEBUT,UMP.LASTGAME,DEATHDATE,DEATH.CITY,DEATH.STATE,DEATH.COUNTRY,BATS,THROWS,HEIGHT,WEIGHT,CEMETERY,CEME.CITY,CEME.STATE,CEME.COUNTRY,CEME.NOTE,BIRTH.NAME,NAME.CHG,BAT.CHG,HOF
1,aardd001,Aardsma,David Allan,David,12/27/1981,Denver,Colorado,USA,04/06/2004,08/23/2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,R,6-05,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aaroh101,Aaron,Henry Louis,Hank,02/05/1934,Mobile,Alabama,USA,04/13/1954,10/03/1976,NaN,NaN,NaN,NaN,NaN,NaN,01/22/2021,Atlanta,Georgia,USA,R,R,6-00,180,Southview Cemetery,Atlanta,Georgia,USA,NaN,NaN,NaN,NaN,HOF
3,aarot101,Aaron,Tommie Lee,Tommie,08/05/1939,Mobile,Alabama,USA,04/10/1962,09/26/1971,NaN,NaN,04/06/1979,09/30/1984,NaN,NaN,08/16/1984,Atlanta,Georgia,USA,R,R,6-03,190,Catholic Cemetery,Mobile,Alabama,USA,NaN,NaN,NaN,NaN,NaN
4,aased001,Aase,Donald William,Don,09/08/1954,Orange,California,USA,07/26/1977,10/03/1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,R,6-03,190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN